sudo: false
language: erlang
script:
    - wget -c https://github.com/erlang/rebar3/releases/download/3.12.0/rebar3
    - chmod +x rebar3
    - REBAR3=./rebar3 make ci
otp_release:
    - 22.1
    - 21.3
    - 20.3
    - 19.3
    - 18.3
after_failure: "echo 'logs/raw.log\n'; cat logs/raw.log; for f in `find logs/ct_run*/log*/ -type f`; do echo \"\n$f\n\" ; cat $f; done"
