sudo: false
language: erlang
script: "rebar3 eunit"
otp_release:
    - 20.0
    - 19.3
    - 19.2
    - 19.1
    - 19.0
    - 18.3
    - 18.2.1
    - 18.2
    - 18.1
    - 18.0
after_failure: "echo 'logs/raw.log\n'; cat logs/raw.log; for f in `find logs/ct_run*/log*/ -type f`; do echo \"\n$f\n\" ; cat $f; done"
