name: CI

on:
  push:
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Run tests on OTP ${{matrix.otp}}
    strategy:
      matrix:
        otp: [21.3, 22.3, 23.3, 24.1]
    container:
      image: erlang:${{ matrix.otp }}-alpine
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Compile
      run: rebar3 compile
    - name: Tests
      run: |
           rebar3 xref
           rebar3 dialyzer
           rebar3 eunit
           rebar3 ct
